name: neucalcu
description: A new Flutter application.

publish_to: 'none'

version: 1.2.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_circle_color_picker: ^0.2.0
  flutter_money_formatter: ^0.8.3
  google_fonts: ^1.1.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  line_awesome_icons: ^1.0.4+2
  math_expressions: ^2.0.0
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

dependency_overrides:
  dartx: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

